// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: shipment_service.proto

#include "shipment_service.pb.h"
#include "shipment_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace com {
namespace cps2004 {

static const char* ShipmentService_method_names[] = {
  "/com.cps2004.ShipmentService/CalculateTotalPrice",
};

std::unique_ptr< ShipmentService::Stub> ShipmentService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ShipmentService::Stub> stub(new ShipmentService::Stub(channel, options));
  return stub;
}

ShipmentService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CalculateTotalPrice_(ShipmentService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ShipmentService::Stub::CalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::com::cps2004::CalculateTotalPriceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::com::cps2004::CalculateTotalPriceRequest, ::com::cps2004::CalculateTotalPriceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CalculateTotalPrice_, context, request, response);
}

void ShipmentService::Stub::async::CalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest* request, ::com::cps2004::CalculateTotalPriceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::com::cps2004::CalculateTotalPriceRequest, ::com::cps2004::CalculateTotalPriceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateTotalPrice_, context, request, response, std::move(f));
}

void ShipmentService::Stub::async::CalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest* request, ::com::cps2004::CalculateTotalPriceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateTotalPrice_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::com::cps2004::CalculateTotalPriceResponse>* ShipmentService::Stub::PrepareAsyncCalculateTotalPriceRaw(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::com::cps2004::CalculateTotalPriceResponse, ::com::cps2004::CalculateTotalPriceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CalculateTotalPrice_, context, request);
}

::grpc::ClientAsyncResponseReader< ::com::cps2004::CalculateTotalPriceResponse>* ShipmentService::Stub::AsyncCalculateTotalPriceRaw(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCalculateTotalPriceRaw(context, request, cq);
  result->StartCall();
  return result;
}

ShipmentService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShipmentService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShipmentService::Service, ::com::cps2004::CalculateTotalPriceRequest, ::com::cps2004::CalculateTotalPriceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShipmentService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::com::cps2004::CalculateTotalPriceRequest* req,
             ::com::cps2004::CalculateTotalPriceResponse* resp) {
               return service->CalculateTotalPrice(ctx, req, resp);
             }, this)));
}

ShipmentService::Service::~Service() {
}

::grpc::Status ShipmentService::Service::CalculateTotalPrice(::grpc::ServerContext* context, const ::com::cps2004::CalculateTotalPriceRequest* request, ::com::cps2004::CalculateTotalPriceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace com
}  // namespace cps2004

