// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: shipment_service.proto
#ifndef GRPC_shipment_5fservice_2eproto__INCLUDED
#define GRPC_shipment_5fservice_2eproto__INCLUDED

#include "shipment_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace com {
namespace cps2004 {

class ShipmentService final {
 public:
  static constexpr char const* service_full_name() {
    return "com.cps2004.ShipmentService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::com::cps2004::CalculateTotalPriceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::cps2004::CalculateTotalPriceResponse>> AsyncCalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::cps2004::CalculateTotalPriceResponse>>(AsyncCalculateTotalPriceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::cps2004::CalculateTotalPriceResponse>> PrepareAsyncCalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::com::cps2004::CalculateTotalPriceResponse>>(PrepareAsyncCalculateTotalPriceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest* request, ::com::cps2004::CalculateTotalPriceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest* request, ::com::cps2004::CalculateTotalPriceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::com::cps2004::CalculateTotalPriceResponse>* AsyncCalculateTotalPriceRaw(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::com::cps2004::CalculateTotalPriceResponse>* PrepareAsyncCalculateTotalPriceRaw(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::com::cps2004::CalculateTotalPriceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::cps2004::CalculateTotalPriceResponse>> AsyncCalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::cps2004::CalculateTotalPriceResponse>>(AsyncCalculateTotalPriceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::cps2004::CalculateTotalPriceResponse>> PrepareAsyncCalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::com::cps2004::CalculateTotalPriceResponse>>(PrepareAsyncCalculateTotalPriceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest* request, ::com::cps2004::CalculateTotalPriceResponse* response, std::function<void(::grpc::Status)>) override;
      void CalculateTotalPrice(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest* request, ::com::cps2004::CalculateTotalPriceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::com::cps2004::CalculateTotalPriceResponse>* AsyncCalculateTotalPriceRaw(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::com::cps2004::CalculateTotalPriceResponse>* PrepareAsyncCalculateTotalPriceRaw(::grpc::ClientContext* context, const ::com::cps2004::CalculateTotalPriceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CalculateTotalPrice_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CalculateTotalPrice(::grpc::ServerContext* context, const ::com::cps2004::CalculateTotalPriceRequest* request, ::com::cps2004::CalculateTotalPriceResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CalculateTotalPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CalculateTotalPrice() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CalculateTotalPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateTotalPrice(::grpc::ServerContext* /*context*/, const ::com::cps2004::CalculateTotalPriceRequest* /*request*/, ::com::cps2004::CalculateTotalPriceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculateTotalPrice(::grpc::ServerContext* context, ::com::cps2004::CalculateTotalPriceRequest* request, ::grpc::ServerAsyncResponseWriter< ::com::cps2004::CalculateTotalPriceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CalculateTotalPrice<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CalculateTotalPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CalculateTotalPrice() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::com::cps2004::CalculateTotalPriceRequest, ::com::cps2004::CalculateTotalPriceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::com::cps2004::CalculateTotalPriceRequest* request, ::com::cps2004::CalculateTotalPriceResponse* response) { return this->CalculateTotalPrice(context, request, response); }));}
    void SetMessageAllocatorFor_CalculateTotalPrice(
        ::grpc::MessageAllocator< ::com::cps2004::CalculateTotalPriceRequest, ::com::cps2004::CalculateTotalPriceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::com::cps2004::CalculateTotalPriceRequest, ::com::cps2004::CalculateTotalPriceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CalculateTotalPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateTotalPrice(::grpc::ServerContext* /*context*/, const ::com::cps2004::CalculateTotalPriceRequest* /*request*/, ::com::cps2004::CalculateTotalPriceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculateTotalPrice(
      ::grpc::CallbackServerContext* /*context*/, const ::com::cps2004::CalculateTotalPriceRequest* /*request*/, ::com::cps2004::CalculateTotalPriceResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CalculateTotalPrice<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CalculateTotalPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CalculateTotalPrice() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CalculateTotalPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateTotalPrice(::grpc::ServerContext* /*context*/, const ::com::cps2004::CalculateTotalPriceRequest* /*request*/, ::com::cps2004::CalculateTotalPriceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CalculateTotalPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CalculateTotalPrice() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CalculateTotalPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateTotalPrice(::grpc::ServerContext* /*context*/, const ::com::cps2004::CalculateTotalPriceRequest* /*request*/, ::com::cps2004::CalculateTotalPriceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculateTotalPrice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CalculateTotalPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CalculateTotalPrice() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CalculateTotalPrice(context, request, response); }));
    }
    ~WithRawCallbackMethod_CalculateTotalPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateTotalPrice(::grpc::ServerContext* /*context*/, const ::com::cps2004::CalculateTotalPriceRequest* /*request*/, ::com::cps2004::CalculateTotalPriceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculateTotalPrice(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CalculateTotalPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CalculateTotalPrice() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::com::cps2004::CalculateTotalPriceRequest, ::com::cps2004::CalculateTotalPriceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::com::cps2004::CalculateTotalPriceRequest, ::com::cps2004::CalculateTotalPriceResponse>* streamer) {
                       return this->StreamedCalculateTotalPrice(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CalculateTotalPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CalculateTotalPrice(::grpc::ServerContext* /*context*/, const ::com::cps2004::CalculateTotalPriceRequest* /*request*/, ::com::cps2004::CalculateTotalPriceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCalculateTotalPrice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::com::cps2004::CalculateTotalPriceRequest,::com::cps2004::CalculateTotalPriceResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CalculateTotalPrice<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CalculateTotalPrice<Service > StreamedService;
};

}  // namespace cps2004
}  // namespace com


#endif  // GRPC_shipment_5fservice_2eproto__INCLUDED
