// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shipment_service.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_shipment_5fservice_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_shipment_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "data_structures.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_shipment_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_shipment_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_shipment_5fservice_2eproto;
namespace com {
namespace cps2004 {
class CalculateTotalPriceRequest;
struct CalculateTotalPriceRequestDefaultTypeInternal;
extern CalculateTotalPriceRequestDefaultTypeInternal _CalculateTotalPriceRequest_default_instance_;
class CalculateTotalPriceResponse;
struct CalculateTotalPriceResponseDefaultTypeInternal;
extern CalculateTotalPriceResponseDefaultTypeInternal _CalculateTotalPriceResponse_default_instance_;
}  // namespace cps2004
}  // namespace com
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace com {
namespace cps2004 {

// ===================================================================


// -------------------------------------------------------------------

class CalculateTotalPriceResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.cps2004.CalculateTotalPriceResponse) */ {
 public:
  inline CalculateTotalPriceResponse() : CalculateTotalPriceResponse(nullptr) {}
  ~CalculateTotalPriceResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CalculateTotalPriceResponse(::google::protobuf::internal::ConstantInitialized);

  inline CalculateTotalPriceResponse(const CalculateTotalPriceResponse& from)
      : CalculateTotalPriceResponse(nullptr, from) {}
  CalculateTotalPriceResponse(CalculateTotalPriceResponse&& from) noexcept
    : CalculateTotalPriceResponse() {
    *this = ::std::move(from);
  }

  inline CalculateTotalPriceResponse& operator=(const CalculateTotalPriceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalculateTotalPriceResponse& operator=(CalculateTotalPriceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CalculateTotalPriceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const CalculateTotalPriceResponse* internal_default_instance() {
    return reinterpret_cast<const CalculateTotalPriceResponse*>(
               &_CalculateTotalPriceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CalculateTotalPriceResponse& a, CalculateTotalPriceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(CalculateTotalPriceResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalculateTotalPriceResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CalculateTotalPriceResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CalculateTotalPriceResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CalculateTotalPriceResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CalculateTotalPriceResponse& from) {
    CalculateTotalPriceResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(CalculateTotalPriceResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "com.cps2004.CalculateTotalPriceResponse";
  }
  protected:
  explicit CalculateTotalPriceResponse(::google::protobuf::Arena* arena);
  CalculateTotalPriceResponse(::google::protobuf::Arena* arena, const CalculateTotalPriceResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTotalPriceFieldNumber = 1,
  };
  // double totalPrice = 1;
  void clear_totalprice() ;
  double totalprice() const;
  void set_totalprice(double value);

  private:
  double _internal_totalprice() const;
  void _internal_set_totalprice(double value);

  public:
  // @@protoc_insertion_point(class_scope:com.cps2004.CalculateTotalPriceResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    double totalprice_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shipment_5fservice_2eproto;
};// -------------------------------------------------------------------

class CalculateTotalPriceRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.cps2004.CalculateTotalPriceRequest) */ {
 public:
  inline CalculateTotalPriceRequest() : CalculateTotalPriceRequest(nullptr) {}
  ~CalculateTotalPriceRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CalculateTotalPriceRequest(::google::protobuf::internal::ConstantInitialized);

  inline CalculateTotalPriceRequest(const CalculateTotalPriceRequest& from)
      : CalculateTotalPriceRequest(nullptr, from) {}
  CalculateTotalPriceRequest(CalculateTotalPriceRequest&& from) noexcept
    : CalculateTotalPriceRequest() {
    *this = ::std::move(from);
  }

  inline CalculateTotalPriceRequest& operator=(const CalculateTotalPriceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalculateTotalPriceRequest& operator=(CalculateTotalPriceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CalculateTotalPriceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CalculateTotalPriceRequest* internal_default_instance() {
    return reinterpret_cast<const CalculateTotalPriceRequest*>(
               &_CalculateTotalPriceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CalculateTotalPriceRequest& a, CalculateTotalPriceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CalculateTotalPriceRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalculateTotalPriceRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CalculateTotalPriceRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CalculateTotalPriceRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CalculateTotalPriceRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const CalculateTotalPriceRequest& from) {
    CalculateTotalPriceRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(CalculateTotalPriceRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "com.cps2004.CalculateTotalPriceRequest";
  }
  protected:
  explicit CalculateTotalPriceRequest(::google::protobuf::Arena* arena);
  CalculateTotalPriceRequest(::google::protobuf::Arena* arena, const CalculateTotalPriceRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShipmentFieldNumber = 1,
  };
  // .com.cps2004.Shipment shipment = 1;
  bool has_shipment() const;
  void clear_shipment() ;
  const ::com::cps2004::Shipment& shipment() const;
  PROTOBUF_NODISCARD ::com::cps2004::Shipment* release_shipment();
  ::com::cps2004::Shipment* mutable_shipment();
  void set_allocated_shipment(::com::cps2004::Shipment* value);
  void unsafe_arena_set_allocated_shipment(::com::cps2004::Shipment* value);
  ::com::cps2004::Shipment* unsafe_arena_release_shipment();

  private:
  const ::com::cps2004::Shipment& _internal_shipment() const;
  ::com::cps2004::Shipment* _internal_mutable_shipment();

  public:
  // @@protoc_insertion_point(class_scope:com.cps2004.CalculateTotalPriceRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::com::cps2004::Shipment* shipment_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shipment_5fservice_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CalculateTotalPriceRequest

// .com.cps2004.Shipment shipment = 1;
inline bool CalculateTotalPriceRequest::has_shipment() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.shipment_ != nullptr);
  return value;
}
inline const ::com::cps2004::Shipment& CalculateTotalPriceRequest::_internal_shipment() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::com::cps2004::Shipment* p = _impl_.shipment_;
  return p != nullptr ? *p : reinterpret_cast<const ::com::cps2004::Shipment&>(::com::cps2004::_Shipment_default_instance_);
}
inline const ::com::cps2004::Shipment& CalculateTotalPriceRequest::shipment() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:com.cps2004.CalculateTotalPriceRequest.shipment)
  return _internal_shipment();
}
inline void CalculateTotalPriceRequest::unsafe_arena_set_allocated_shipment(::com::cps2004::Shipment* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.shipment_);
  }
  _impl_.shipment_ = reinterpret_cast<::com::cps2004::Shipment*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:com.cps2004.CalculateTotalPriceRequest.shipment)
}
inline ::com::cps2004::Shipment* CalculateTotalPriceRequest::release_shipment() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::com::cps2004::Shipment* released = _impl_.shipment_;
  _impl_.shipment_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::com::cps2004::Shipment* CalculateTotalPriceRequest::unsafe_arena_release_shipment() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:com.cps2004.CalculateTotalPriceRequest.shipment)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::com::cps2004::Shipment* temp = _impl_.shipment_;
  _impl_.shipment_ = nullptr;
  return temp;
}
inline ::com::cps2004::Shipment* CalculateTotalPriceRequest::_internal_mutable_shipment() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.shipment_ == nullptr) {
    auto* p = CreateMaybeMessage<::com::cps2004::Shipment>(GetArena());
    _impl_.shipment_ = reinterpret_cast<::com::cps2004::Shipment*>(p);
  }
  return _impl_.shipment_;
}
inline ::com::cps2004::Shipment* CalculateTotalPriceRequest::mutable_shipment() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::com::cps2004::Shipment* _msg = _internal_mutable_shipment();
  // @@protoc_insertion_point(field_mutable:com.cps2004.CalculateTotalPriceRequest.shipment)
  return _msg;
}
inline void CalculateTotalPriceRequest::set_allocated_shipment(::com::cps2004::Shipment* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.shipment_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.shipment_ = reinterpret_cast<::com::cps2004::Shipment*>(value);
  // @@protoc_insertion_point(field_set_allocated:com.cps2004.CalculateTotalPriceRequest.shipment)
}

// -------------------------------------------------------------------

// CalculateTotalPriceResponse

// double totalPrice = 1;
inline void CalculateTotalPriceResponse::clear_totalprice() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.totalprice_ = 0;
}
inline double CalculateTotalPriceResponse::totalprice() const {
  // @@protoc_insertion_point(field_get:com.cps2004.CalculateTotalPriceResponse.totalPrice)
  return _internal_totalprice();
}
inline void CalculateTotalPriceResponse::set_totalprice(double value) {
  _internal_set_totalprice(value);
  // @@protoc_insertion_point(field_set:com.cps2004.CalculateTotalPriceResponse.totalPrice)
}
inline double CalculateTotalPriceResponse::_internal_totalprice() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.totalprice_;
}
inline void CalculateTotalPriceResponse::_internal_set_totalprice(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.totalprice_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace cps2004
}  // namespace com


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_shipment_5fservice_2eproto_2epb_2eh
