// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shipment_cost.proto

package com.cps2004;

public final class ShipmentCost {
  private ShipmentCost() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CalculateTotalPriceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cps2004.CalculateTotalPriceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.cps2004.Shipment shipments = 1;</code>
     * @return Whether the shipments field is set.
     */
    boolean hasShipments();
    /**
     * <code>.com.cps2004.Shipment shipments = 1;</code>
     * @return The shipments.
     */
    com.cps2004.DataStructures.Shipment getShipments();
    /**
     * <code>.com.cps2004.Shipment shipments = 1;</code>
     */
    com.cps2004.DataStructures.ShipmentOrBuilder getShipmentsOrBuilder();
  }
  /**
   * Protobuf type {@code com.cps2004.CalculateTotalPriceRequest}
   */
  public static final class CalculateTotalPriceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cps2004.CalculateTotalPriceRequest)
      CalculateTotalPriceRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CalculateTotalPriceRequest.newBuilder() to construct.
    private CalculateTotalPriceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CalculateTotalPriceRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CalculateTotalPriceRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cps2004.ShipmentCost.internal_static_com_cps2004_CalculateTotalPriceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cps2004.ShipmentCost.internal_static_com_cps2004_CalculateTotalPriceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cps2004.ShipmentCost.CalculateTotalPriceRequest.class, com.cps2004.ShipmentCost.CalculateTotalPriceRequest.Builder.class);
    }

    public static final int SHIPMENTS_FIELD_NUMBER = 1;
    private com.cps2004.DataStructures.Shipment shipments_;
    /**
     * <code>.com.cps2004.Shipment shipments = 1;</code>
     * @return Whether the shipments field is set.
     */
    @java.lang.Override
    public boolean hasShipments() {
      return shipments_ != null;
    }
    /**
     * <code>.com.cps2004.Shipment shipments = 1;</code>
     * @return The shipments.
     */
    @java.lang.Override
    public com.cps2004.DataStructures.Shipment getShipments() {
      return shipments_ == null ? com.cps2004.DataStructures.Shipment.getDefaultInstance() : shipments_;
    }
    /**
     * <code>.com.cps2004.Shipment shipments = 1;</code>
     */
    @java.lang.Override
    public com.cps2004.DataStructures.ShipmentOrBuilder getShipmentsOrBuilder() {
      return shipments_ == null ? com.cps2004.DataStructures.Shipment.getDefaultInstance() : shipments_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (shipments_ != null) {
        output.writeMessage(1, getShipments());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (shipments_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getShipments());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cps2004.ShipmentCost.CalculateTotalPriceRequest)) {
        return super.equals(obj);
      }
      com.cps2004.ShipmentCost.CalculateTotalPriceRequest other = (com.cps2004.ShipmentCost.CalculateTotalPriceRequest) obj;

      if (hasShipments() != other.hasShipments()) return false;
      if (hasShipments()) {
        if (!getShipments()
            .equals(other.getShipments())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasShipments()) {
        hash = (37 * hash) + SHIPMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getShipments().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cps2004.ShipmentCost.CalculateTotalPriceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cps2004.CalculateTotalPriceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cps2004.CalculateTotalPriceRequest)
        com.cps2004.ShipmentCost.CalculateTotalPriceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cps2004.ShipmentCost.internal_static_com_cps2004_CalculateTotalPriceRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cps2004.ShipmentCost.internal_static_com_cps2004_CalculateTotalPriceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cps2004.ShipmentCost.CalculateTotalPriceRequest.class, com.cps2004.ShipmentCost.CalculateTotalPriceRequest.Builder.class);
      }

      // Construct using com.cps2004.ShipmentCost.CalculateTotalPriceRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        shipments_ = null;
        if (shipmentsBuilder_ != null) {
          shipmentsBuilder_.dispose();
          shipmentsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cps2004.ShipmentCost.internal_static_com_cps2004_CalculateTotalPriceRequest_descriptor;
      }

      @java.lang.Override
      public com.cps2004.ShipmentCost.CalculateTotalPriceRequest getDefaultInstanceForType() {
        return com.cps2004.ShipmentCost.CalculateTotalPriceRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.cps2004.ShipmentCost.CalculateTotalPriceRequest build() {
        com.cps2004.ShipmentCost.CalculateTotalPriceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cps2004.ShipmentCost.CalculateTotalPriceRequest buildPartial() {
        com.cps2004.ShipmentCost.CalculateTotalPriceRequest result = new com.cps2004.ShipmentCost.CalculateTotalPriceRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.cps2004.ShipmentCost.CalculateTotalPriceRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.shipments_ = shipmentsBuilder_ == null
              ? shipments_
              : shipmentsBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cps2004.ShipmentCost.CalculateTotalPriceRequest) {
          return mergeFrom((com.cps2004.ShipmentCost.CalculateTotalPriceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cps2004.ShipmentCost.CalculateTotalPriceRequest other) {
        if (other == com.cps2004.ShipmentCost.CalculateTotalPriceRequest.getDefaultInstance()) return this;
        if (other.hasShipments()) {
          mergeShipments(other.getShipments());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getShipmentsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.cps2004.DataStructures.Shipment shipments_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cps2004.DataStructures.Shipment, com.cps2004.DataStructures.Shipment.Builder, com.cps2004.DataStructures.ShipmentOrBuilder> shipmentsBuilder_;
      /**
       * <code>.com.cps2004.Shipment shipments = 1;</code>
       * @return Whether the shipments field is set.
       */
      public boolean hasShipments() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.com.cps2004.Shipment shipments = 1;</code>
       * @return The shipments.
       */
      public com.cps2004.DataStructures.Shipment getShipments() {
        if (shipmentsBuilder_ == null) {
          return shipments_ == null ? com.cps2004.DataStructures.Shipment.getDefaultInstance() : shipments_;
        } else {
          return shipmentsBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.cps2004.Shipment shipments = 1;</code>
       */
      public Builder setShipments(com.cps2004.DataStructures.Shipment value) {
        if (shipmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          shipments_ = value;
        } else {
          shipmentsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.cps2004.Shipment shipments = 1;</code>
       */
      public Builder setShipments(
          com.cps2004.DataStructures.Shipment.Builder builderForValue) {
        if (shipmentsBuilder_ == null) {
          shipments_ = builderForValue.build();
        } else {
          shipmentsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.cps2004.Shipment shipments = 1;</code>
       */
      public Builder mergeShipments(com.cps2004.DataStructures.Shipment value) {
        if (shipmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            shipments_ != null &&
            shipments_ != com.cps2004.DataStructures.Shipment.getDefaultInstance()) {
            getShipmentsBuilder().mergeFrom(value);
          } else {
            shipments_ = value;
          }
        } else {
          shipmentsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.cps2004.Shipment shipments = 1;</code>
       */
      public Builder clearShipments() {
        bitField0_ = (bitField0_ & ~0x00000001);
        shipments_ = null;
        if (shipmentsBuilder_ != null) {
          shipmentsBuilder_.dispose();
          shipmentsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.cps2004.Shipment shipments = 1;</code>
       */
      public com.cps2004.DataStructures.Shipment.Builder getShipmentsBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getShipmentsFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.cps2004.Shipment shipments = 1;</code>
       */
      public com.cps2004.DataStructures.ShipmentOrBuilder getShipmentsOrBuilder() {
        if (shipmentsBuilder_ != null) {
          return shipmentsBuilder_.getMessageOrBuilder();
        } else {
          return shipments_ == null ?
              com.cps2004.DataStructures.Shipment.getDefaultInstance() : shipments_;
        }
      }
      /**
       * <code>.com.cps2004.Shipment shipments = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cps2004.DataStructures.Shipment, com.cps2004.DataStructures.Shipment.Builder, com.cps2004.DataStructures.ShipmentOrBuilder> 
          getShipmentsFieldBuilder() {
        if (shipmentsBuilder_ == null) {
          shipmentsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.cps2004.DataStructures.Shipment, com.cps2004.DataStructures.Shipment.Builder, com.cps2004.DataStructures.ShipmentOrBuilder>(
                  getShipments(),
                  getParentForChildren(),
                  isClean());
          shipments_ = null;
        }
        return shipmentsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cps2004.CalculateTotalPriceRequest)
    }

    // @@protoc_insertion_point(class_scope:com.cps2004.CalculateTotalPriceRequest)
    private static final com.cps2004.ShipmentCost.CalculateTotalPriceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cps2004.ShipmentCost.CalculateTotalPriceRequest();
    }

    public static com.cps2004.ShipmentCost.CalculateTotalPriceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalculateTotalPriceRequest>
        PARSER = new com.google.protobuf.AbstractParser<CalculateTotalPriceRequest>() {
      @java.lang.Override
      public CalculateTotalPriceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CalculateTotalPriceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalculateTotalPriceRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cps2004.ShipmentCost.CalculateTotalPriceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CalculateTotalPriceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cps2004.CalculateTotalPriceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double totalPrice = 1;</code>
     * @return The totalPrice.
     */
    double getTotalPrice();
  }
  /**
   * Protobuf type {@code com.cps2004.CalculateTotalPriceResponse}
   */
  public static final class CalculateTotalPriceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cps2004.CalculateTotalPriceResponse)
      CalculateTotalPriceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CalculateTotalPriceResponse.newBuilder() to construct.
    private CalculateTotalPriceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CalculateTotalPriceResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CalculateTotalPriceResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cps2004.ShipmentCost.internal_static_com_cps2004_CalculateTotalPriceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cps2004.ShipmentCost.internal_static_com_cps2004_CalculateTotalPriceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cps2004.ShipmentCost.CalculateTotalPriceResponse.class, com.cps2004.ShipmentCost.CalculateTotalPriceResponse.Builder.class);
    }

    public static final int TOTALPRICE_FIELD_NUMBER = 1;
    private double totalPrice_ = 0D;
    /**
     * <code>double totalPrice = 1;</code>
     * @return The totalPrice.
     */
    @java.lang.Override
    public double getTotalPrice() {
      return totalPrice_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(totalPrice_) != 0) {
        output.writeDouble(1, totalPrice_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(totalPrice_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, totalPrice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cps2004.ShipmentCost.CalculateTotalPriceResponse)) {
        return super.equals(obj);
      }
      com.cps2004.ShipmentCost.CalculateTotalPriceResponse other = (com.cps2004.ShipmentCost.CalculateTotalPriceResponse) obj;

      if (java.lang.Double.doubleToLongBits(getTotalPrice())
          != java.lang.Double.doubleToLongBits(
              other.getTotalPrice())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOTALPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTotalPrice()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cps2004.ShipmentCost.CalculateTotalPriceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cps2004.CalculateTotalPriceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cps2004.CalculateTotalPriceResponse)
        com.cps2004.ShipmentCost.CalculateTotalPriceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cps2004.ShipmentCost.internal_static_com_cps2004_CalculateTotalPriceResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cps2004.ShipmentCost.internal_static_com_cps2004_CalculateTotalPriceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cps2004.ShipmentCost.CalculateTotalPriceResponse.class, com.cps2004.ShipmentCost.CalculateTotalPriceResponse.Builder.class);
      }

      // Construct using com.cps2004.ShipmentCost.CalculateTotalPriceResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        totalPrice_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cps2004.ShipmentCost.internal_static_com_cps2004_CalculateTotalPriceResponse_descriptor;
      }

      @java.lang.Override
      public com.cps2004.ShipmentCost.CalculateTotalPriceResponse getDefaultInstanceForType() {
        return com.cps2004.ShipmentCost.CalculateTotalPriceResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.cps2004.ShipmentCost.CalculateTotalPriceResponse build() {
        com.cps2004.ShipmentCost.CalculateTotalPriceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cps2004.ShipmentCost.CalculateTotalPriceResponse buildPartial() {
        com.cps2004.ShipmentCost.CalculateTotalPriceResponse result = new com.cps2004.ShipmentCost.CalculateTotalPriceResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.cps2004.ShipmentCost.CalculateTotalPriceResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.totalPrice_ = totalPrice_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cps2004.ShipmentCost.CalculateTotalPriceResponse) {
          return mergeFrom((com.cps2004.ShipmentCost.CalculateTotalPriceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cps2004.ShipmentCost.CalculateTotalPriceResponse other) {
        if (other == com.cps2004.ShipmentCost.CalculateTotalPriceResponse.getDefaultInstance()) return this;
        if (other.getTotalPrice() != 0D) {
          setTotalPrice(other.getTotalPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                totalPrice_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double totalPrice_ ;
      /**
       * <code>double totalPrice = 1;</code>
       * @return The totalPrice.
       */
      @java.lang.Override
      public double getTotalPrice() {
        return totalPrice_;
      }
      /**
       * <code>double totalPrice = 1;</code>
       * @param value The totalPrice to set.
       * @return This builder for chaining.
       */
      public Builder setTotalPrice(double value) {

        totalPrice_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double totalPrice = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalPrice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        totalPrice_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cps2004.CalculateTotalPriceResponse)
    }

    // @@protoc_insertion_point(class_scope:com.cps2004.CalculateTotalPriceResponse)
    private static final com.cps2004.ShipmentCost.CalculateTotalPriceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cps2004.ShipmentCost.CalculateTotalPriceResponse();
    }

    public static com.cps2004.ShipmentCost.CalculateTotalPriceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalculateTotalPriceResponse>
        PARSER = new com.google.protobuf.AbstractParser<CalculateTotalPriceResponse>() {
      @java.lang.Override
      public CalculateTotalPriceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CalculateTotalPriceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalculateTotalPriceResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cps2004.ShipmentCost.CalculateTotalPriceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cps2004_CalculateTotalPriceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cps2004_CalculateTotalPriceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cps2004_CalculateTotalPriceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cps2004_CalculateTotalPriceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023shipment_cost.proto\022\013com.cps2004\032\025data" +
      "_structures.proto\"F\n\032CalculateTotalPrice" +
      "Request\022(\n\tshipments\030\001 \001(\0132\025.com.cps2004" +
      ".Shipment\"1\n\033CalculateTotalPriceResponse" +
      "\022\022\n\ntotalPrice\030\001 \001(\0012{\n\017ShipmentService\022" +
      "h\n\023CalculateTotalPrice\022\'.com.cps2004.Cal" +
      "culateTotalPriceRequest\032(.com.cps2004.Ca" +
      "lculateTotalPriceResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cps2004.DataStructures.getDescriptor(),
        });
    internal_static_com_cps2004_CalculateTotalPriceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cps2004_CalculateTotalPriceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cps2004_CalculateTotalPriceRequest_descriptor,
        new java.lang.String[] { "Shipments", });
    internal_static_com_cps2004_CalculateTotalPriceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cps2004_CalculateTotalPriceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cps2004_CalculateTotalPriceResponse_descriptor,
        new java.lang.String[] { "TotalPrice", });
    com.cps2004.DataStructures.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
